### ISSUE TITLE
'Upload Image' functionality not working in Firefox

### ISSUE THREAD

**Issue by vdalv** [Microsoft/onnxjs-demo#15]
Firefox version: 63.0.3 (64-bit)

Action: User clicks the 'UPLOAD IMAGE' button on any of the demos (excluding MNIST ofc).
Expected: The open file dialog should appear and allow the user to select an image to upload.
Actual: Nothing happens, no errors appear in the UI or console.

Note: Works as expected on Google Chrome v70.0.3538.110 (Official Build) (64-bit)

**Comment by liuziyue** [comment]
Thanks for the feedback. #17 addresses this issue.
