### ISSUE TITLE
Asking about order of RGB channels

### ISSUE THREAD

**Issue by NTT123** [Microsoft/onnxjs-demo#18]
https://github.com/Microsoft/onnxjs-demo/blob/5499e5dbaf779896882755604162a4c15161a65b/src/components/models/Resnet50.vue#L48-L50

I wonder why the order of RGB channels are reversed?

**Comment by liuziyue** [comment]
It seems to be a typo. The order should not be reversed. Thanks for the catch. I'll submit a pr about this.

**Comment by NTT123** [comment]
There are also "reversed orders"  in Yolo.vue and and Squeezenet.vue
