### ISSUE TITLE
Demo for video processing

### ISSUE THREAD

**Issue by euler16** [Microsoft/onnxjs-demo#20]
I want to create a video classification demo where I record a fixed frame length video (in browser), and then give feed it into an onnx model. Could you tell me how to do so? as in the problem boils down to taking the video input into Float32Arrays

**Comment by astu9880** [comment]
I don't know why the demo is 'opensourced' when the authors have uploaded the obfuscated source code.

**Comment by euler16** [comment]
I was able to do it just an hour ago. I took from camera using opencv.js , and kept the frames as float32Array and it worked !. The only issue was that Onnx.js apparently doesn't support 'Shape' (that was the error message) (same as that mentioned [here](https://github.com/Microsoft/onnxjs/issues/84) ).

**Comment by Tylersuard** [comment]
@euler16 Could you help me out with this?  I'm trying to swap out the YOLO demo's model with my own custom-trained YOLOv5  model, having a hard time with it.
